### ISSUE TITLE
Program doesn't recognize when other user is disconnected 

### ISSUE THREAD

**Issue by Dylan-Motz** [Team-Controller-NAU/Controller#201]

**Comment by Dylan-Motz** [comment]
Clearing error when disconnected??!!

**Comment by Dylan-Motz** [comment]
Add a listener

**Comment by bradd07** [comment]
disconnect message not being received MOST of the time?

**Comment by bradd07** [comment]
I believe clearError is not checking connection before using transmit
(transmit only checks the connection/status of one port, not the other)

**Comment by bcu8** [comment]
timeout on "time since last message" timer causes disconnect after a certain amount of time (adjustable in user settings)
