### ISSUE TITLE
Unrecognized serial message 

### ISSUE THREAD

**Issue by Dylan-Motz** [Team-Controller-NAU/Controller#202]

**Comment by bcu8** [comment]
be sure to check the drivers that get installed on each system and also test on different combos of peoples pcs

**Comment by bradd07** [comment]
Unrecognized serial message received :  "\u00016,7,\n"

**Comment by bcu8** [comment]
try QT's toUTF-8() and Latin1() functions, also research alternatives. We need reliable deserialization and to my understanding a serialized string can represent more than 1 thing at once, Ex.. "9,\n" and "\u00006" simultaneously

**Comment by bcu8** [comment]
check string length maybe utf-8 non printable characters are making it into the string
