### ISSUE TITLE
Uniquely identify errors/events across different controller sessions

### ISSUE THREAD

**Issue by bcu8** [Team-Controller-NAU/Controller#24]
Find strategy, consider the potential issues and edge cases

**Comment by zjp292** [comment]
Assigned as research issue. Submit doc with findings.

**Comment by zjp292** [comment]
Using [D:H:M:S] as a unique identifier. Consider all cases, determine if possible. Present findings at next client meeting.

**Comment by bradd07** [comment]
DDM/GUI get somewhat messy after starting a new controller session as well - blurring between two sessions
