### ISSUE TITLE
If left running program will run out of RAM and crash

### ISSUE THREAD

**Issue by bcu8** [Team-Controller-NAU/Controller#47]
possible solutions:
============
1. Consider keeping a cap on the number of total nodes allowed. If cap is reached a log file output will be called and x% of events and errors get freed from list. 

2. if there is a qt method of finding out how much RAM is available and how much is currently used, we could use this intel to dynamically remove earliest nodes and output them to log file.

#include <QCoreApplication>
#include <QDebug>

#ifdef Q_OS_WIN
#include <windows.h>
#elif defined(Q_OS_LINUX)
#include <sys/sysinfo.h>
#elif defined(Q_OS_MACOS)
#include <sys/sysctl.h>
#include <mach/mach.h>
#endif

#ifdef Q_OS_WIN
// Windows specific function to get available RAM
qint64 availableRAM() {
    MEMORYSTATUSEX status;
    status.dwLength = sizeof(status);
    GlobalMemoryStatusEx(&status);
    return status.ullAvailPhys;
}
#elif defined(Q_OS_LINUX)
// Linux specific function to get available RAM
qint64 availableRAM() {
    struct sysinfo memInfo;
    sysinfo(&memInfo);
    return memInfo.freeram * memInfo.mem_unit;
}
#elif defined(Q_OS_MACOS)
// macOS specific function to get available RAM
qint64 availableRAM() {
    mach_port_t host_port = mach_host_self();
    mach_msg_type_number_t host_size = sizeof(vm_statistics_data_t) / sizeof(integer_t);
    vm_size_t page_size;
    vm_statistics_data_t vm_stat;
    if (host_page_size(host_port, &page_size) != KERN_SUCCESS) {
        return -1;
    }
    if (host_statistics(host_port, HOST_VM_INFO, (host_info_t)&vm_stat, &host_size) != KERN_SUCCESS) {
        return -1;
    }
    natural_t free_count = vm_stat.free_count;
    return (qint64)free_count * (qint64)page_size;
}
#endif

int main(int argc, char *argv[]) {
    QCoreApplication a(argc, argv);

    qint64 ram = availableRAM();
    qDebug() << "Available RAM: " << ram << " bytes";

    return a.exec();
}

**Comment by zjp292** [comment]
helpful stuff we found in the meeting:
https://stackoverflow.com/questions/21521042/c-program-to-figure-out-how-much-memory-my-computer-has
pinned code snippet from Brandon in general
